### ISSUE TITLE
Move `edu.gemini` to `s01.oss.sonatype.org`?

### ISSUE THREAD

**Issue by armanbilge** [gemini-hlsw/sbt-lucuma#137]
Lots of good reasons to do so documented at https://github.com/typelevel/sbt-typelevel/issues/84, and @tpolecat has successfully done this for his personal groupid.

**Comment by cquiroz** [comment]
Do you mean that we publish the libs to the `s01` host? Do they go to maven central eventually?
Can we use them after publication without waiting to get to maven central?

Seems fine to me

**Comment by armanbilge** [comment]
Yes, they do get synced to maven central and and you can use them immediately by adding `s01.oss.sonatype.org` to your resolvers. I have a PR open to get this built-in to sbt:
- https://github.com/sbt/librarymanagement/pull/392

To do the migration you need to open an issue on the sonatype jira requesting that they move you to S01.

**Comment by armanbilge** [comment]
Btw, do you use org-wide secrets or per-repo secrets? It might be good to switch to org-wide secrets so you can update them quickly.

Another secret that would be good to change is your PGP key: currently it is passphrase-protected, which works with sbt-typelevel but should be considered legacy mode. The better thing to do is add a non-passphrase-protected key.

**Comment by cquiroz** [comment]
What's the reason for no passphrase?
Settings should org-wide mostly

**Comment by armanbilge** [comment]
The passphrase issue is discussed here: https://github.com/typelevel/sbt-typelevel/discussions/9#discussioncomment-1251774

> The fact that it allows you to pass in gpg passwords is somewhat meaningless since it doesn't change the security model, which is why sbt-gpg just doesn't bother. I get that everything involving GPG is a pain in the ass, but at the same time, it's a single command to export a private key without a password, and you only have to do it once. That seems a small price to pay for a plugin which uses gpg in its most secure and updated mode.

**Comment by cquiroz** [comment]
Should we merge this and produce new keys. I think we have set project level keys rather than org-wide keys

**Comment by armanbilge** [comment]
There's nothing to merge, sbt-typelevel will automatically detect which kind of key you have.

The way forward is to produce a new unpassphrased key and set it as an org-wide secret. Then on each project to remove the secret key and secret passphrase and it will use the org one instead.

**Comment by cquiroz** [comment]
Ok, Let's do that

**Comment by cquiroz** [comment]
Do we need to set only PGP_SECRET then?

**Comment by armanbilge** [comment]
Yes, exactly. And it's very important to remove `PGP_PASSPHRASE` from each repo b/c that's how it figures out which kind of key you have.

**Comment by cquiroz** [comment]
Right, I changed the key and we need to inform sonatype then?

**Comment by armanbilge** [comment]
If you generated a new key you need to upload it to a key server.

https://pgp.mit.edu/
https://keyserver.ubuntu.com/

I usually do both because sometimes they're flaky.

If you re-exported an existing key then it should already be in the key server.

**Comment by armanbilge** [comment]
Linking to https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-77856

**Comment by armanbilge** [comment]
I think we can close this one, the migration is effectively done.
