### ISSUE TITLE
Default JDK?

### ISSUE THREAD

**Issue by armanbilge** [gemini-hlsw/sbt-lucuma#139]
The sbt-typelevel default is JDK8, but if you are using something newer that's cool.

**Comment by cquiroz** [comment]
We are kind of steering towards jdk 17 though maybe we should keep publishing for 8

**Comment by armanbilge** [comment]
We should check both in CI then.

**Comment by armanbilge** [comment]
https://github.com/gemini-hlsw/sbt-lucuma/pull/138 checks both 8 and 17.
