### ISSUE TITLE
set up header creation on compile

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/sbt-lucuma#23]
the header plugin is configured but not set up to write headers automatically

**Comment by armanbilge** [comment]
Do you still want this? I actually repealed this feature from sbt-typelevel because it can be trippy for CI, see:
- https://github.com/typelevel/sbt-typelevel/pull/86

**Comment by cquiroz** [comment]
We have normally just created them when needed, often it trips CI when you forget but that's not too bad. It seems fine to leave it as that

**Comment by armanbilge** [comment]
Cool, can probably close this issue then 👍

**Comment by armanbilge** [comment]
This was enabled in https://github.com/gemini-hlsw/sbt-lucuma/pull/145.
