### ISSUE TITLE
Share scalastyle settings

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/sbt-lucuma#9]
If we are going to use scalastyle, the configuration should be shared across projects.

**Comment by armanbilge** [comment]
Scalastyle is old I think, but this applies to scalafmt. I proposed one way to implement this in https://github.com/typelevel/sbt-typelevel/issues/103:
- https://github.com/typelevel/sbt-typelevel/issues/103

**Comment by cquiroz** [comment]
We are not using scalastyle anymore. Some of our projects do use `scalafmt` and I'd really like to have a shared config. Now changes are manually copied across projects

**Comment by armanbilge** [comment]
@cquiroz which repo can I grab your preferred config from? To set as the shared config.

**Comment by cquiroz** [comment]
I guess explore, BTW that config is probably obsolete, it was developed from bits and pieces back on the inital days of scalafmt. Maybe it can be improved

https://github.com/gemini-hlsw/explore/blob/master/.scalafmt.conf

**Comment by armanbilge** [comment]
Thanks :) sure, once it's shared it'll be easy to update it.
